use_frameworks!

target 'UIAdapterKit_Example' do
  pod 'UIAdapterKit', :path => '../'
  pod 'Fakery'
  pod 'R.swift', '~> 5.0.3'

  target 'UIAdapterKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
