author: andreadelfante
author_url: https://twitter.com/a_delfante
github_url: https://github.com/andreadelfante/UIAdapterKit
root_url: https://andreadelfante.github.io/UIAdapterKit
module: UIAdapterKit
output: docs
theme: fullwidth
clean: true

xcodebuild_arguments:
    - "-workspace"
    - "Example/UIAdapterKit.xcworkspace"
    - "-scheme"
    - "UIAdapterKit-Example"
