osx_image: xcode10.2
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

cache:
  bundler: true
  cocoapods: true
  directories:
  - ./build
  - ./Example/Pods
  - ./Example/UIAdapterKit.xcworkspace

before_install:
  - gem update --system
  - gem install bundler
  - bundle install

after_script:
  - date

jobs:
  include:
    - stage: lint
      name: "Code quality"
      script: bundle exec fastlane code_lint
    - stage: lint
      name: "Podspec quality"
      script: bundle exec fastlane podspec_lint
    - stage: test
      name: "Test (Debug)"
      script: bundle exec fastlane test_debug
